import { describe, it, expect } from "vitest";
import {
  prgFloats,
  hexToSeed,
  seedToHex,
  derivePairwiseMask,
  maskUpdate,
  pairKey,
  MASK_SCALE,
} from "../src/index.js";

/**
 * GOLDEN cross-language PRG vector. Seed = 32 bytes of 0x01. These exact float
 * literals were generated by RUNNING the canonical Python implementation
 * (veritas_core.secure_agg.prg_floats) and are ALSO hardcoded in the Python test
 * (core/tests/test_secure_agg.py::GOLDEN_PRG_FLOATS). Asserting the same
 * literals in BOTH languages is what proves the byte-for-byte interop claim —
 * this test is NOT a trivial all-TS tautology; it checks against the canonical
 * Python-generated numbers.
 */
const GOLDEN_SEED_HEX = "01".repeat(32);
const GOLDEN_PRG_FLOATS = [
  0.8049047642420114, 0.77533269603633, 0.13199360046164554, 0.8898936262059701,
];

describe("canonical cross-language PRG", () => {
  it("matches the golden Python-generated vector byte-for-byte", () => {
    const out = prgFloats(hexToSeed(GOLDEN_SEED_HEX), 4);
    expect(out).toEqual(GOLDEN_PRG_FLOATS);
  });

  it("produces uniforms in [0,1) and is deterministic", () => {
    const a = prgFloats(hexToSeed(GOLDEN_SEED_HEX), 16);
    const b = prgFloats(hexToSeed(GOLDEN_SEED_HEX), 16);
    expect(a).toEqual(b);
    for (const x of a) {
      expect(x).toBeGreaterThanOrEqual(0);
      expect(x).toBeLessThan(1);
    }
  });

  it("seed hex round-trips to 32 bytes", () => {
    const seed = hexToSeed(GOLDEN_SEED_HEX);
    expect(seed.length).toBe(32);
    expect(seedToHex(seed)).toBe(GOLDEN_SEED_HEX);
  });

  it("derivePairwiseMask maps the golden uniforms onto the mask scale", () => {
    const mask = derivePairwiseMask(GOLDEN_SEED_HEX, 4);
    for (let i = 0; i < 4; i++) {
      expect(mask[i]).toBeCloseTo((GOLDEN_PRG_FLOATS[i]! * 2 - 1) * MASK_SCALE, 6);
    }
  });

  it("two parties' masks cancel exactly under id-ordered signs", () => {
    const seed = "1234abcd".repeat(8);
    const seeds = { [pairKey("devA", "devB")]: seed };
    const dpA = [1, 2, 3, -1];
    const dpB = [0.5, -2, 1, 4];
    const mA = maskUpdate(dpA, "devA", ["devB"], seeds);
    const mB = maskUpdate(dpB, "devB", ["devA"], seeds);
    const sum = mA.map((x, i) => x + mB[i]!);
    const trueSum = dpA.map((x, i) => x + dpB[i]!);
    sum.forEach((s, i) => expect(s).toBeCloseTo(trueSum[i]!, 6));
    // the individual masked vector is dominated by the mask
    expect(mA.every((x, i) => x === dpA[i])).toBe(false);
  });
});
